### ISSUE TITLE
Rotate Admin Token

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#14]
I know it is listed in the "What's missing" section, but I thought we should have an issue to track it.

This plugin should rotate the `admin/config` access_token when it's configured (optionally?)

**Comment by TJM** [comment]
As noted above, this issue would be solved by PR #17

**Comment by EvertonSA** [comment]
hello @TJM, I'm very interested in this feature, what is it missing for master merge?
