### ISSUE TITLE
Doc support with Kubernetes 

### ISSUE THREAD

**Issue by chandrashekarhamse** [jfrog/artifactory-secrets-plugin#20]
I'm not sure if this is the right place to ask this question. It's not a bug just a query!

I have configured the vault to connect artifactory using this plugin to dynamically generate the access token, everything works fine for me.
I want to know how can I call the vault role for artifactory within Kubernetes manifest file to dynamically generate the access token. I checked the vault documentation but I couldn't find it.

Is there any documentation available on how to use it or if someone can share a sample Kubernetes manifest file on how to do that would be helpful?

**Comment by EvertonSA** [comment]
the plugin itself has not much to do with kubernetes, so the issue tittle is a bit confusing. Maybe you need this https://external-secrets.io/v0.6.1/

**Comment by alexhung** [comment]
@EvertonSA Thanks for chiming in!
