### ISSUE TITLE
expires_in=0 ends up with a 1 year token (will this burn is in 1y)

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#25]
> From my (albeit very quick) testing in 7.49.3, setting the `expires_in` field to `0` in the `POST /access/api/v1/tokens` request works to create a non-expiring token. There's no `expires_in` field when `GET /access/api/v1/tokens` and no expiry date in the web UI. I am able to revoke by `DELETE /access/api/v1/tokens/{id}`.
>
> When I create a token with `expires_in` set to a non-zero value (say 900 = 15 min), I was not able to revoke it which is correct behavior.
> 
> ```json
> {
>     "code": "BAD_REQUEST",
>     "message": "Token not revocable",
>     "detail": "Token not revocable. Token expirationTimeMillis: 1673028200098, issuedAtMillis: 1673027300098, revocableExpiryThresholdMillis: 21600000"
> }
> ```

_Originally posted by @alexhung in https://github.com/jfrog/artifactory-secrets-plugin/issues/22#issuecomment-1373974190_
     

We may have to add something to the readme if we can figure out what version that "non-expiring" token thing was fixed in. In the one that the user is referencing (7.33.12), even when expires_in=0, the token still ends up with a one year expiration, but it *does* allow the token to be revoked (curl -X DELETE). I am afraid that our current setup will silently fail 1year from setup due to the "default" 1 year token expiration being applied.

**Comment by alexhung** [comment]
@TJM I've managed to track the change to [7.42.1](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.42.1Cloud)

> Generate a Non-expiry Admin Token without Changing the Configuration
Admins can now bypass tokens restrictions and can generate a token with any expiry they wish and create refreshable tokens without changing the configuration. The token restrictions will affect non-admin users and they can be set in the [Access YAML Configuration](https://www.jfrog.com/confluence/display/JFROG/Access+YAML+Configuration).

I'll be adding a note to the README soon.
