### ISSUE TITLE
Plugin Versioning

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#33]
https://developer.hashicorp.com/vault/docs/release-notes/1.12.0#plugin-versioning

I think we should add a version to the plugin.

**Comment by TJM** [comment]
I am *trying* to figure out how to do this, but have not found any examples yet. It seems easy, on the surface, but I'd like to see how the versioning tag is set/handled by example.

**Comment by alexhung** [comment]
@TJM Same here. I posted to HashiCorp forum and gotten no answer. I saw an example plugin that has a `version.go` with `Version` field. But no comment or anything to indicate if that's how Vault server will look for plugin version.

**Comment by alexhung** [comment]
I reached out to our HashiCorp contact and they confirm that this is the field to set for plugin version: https://github.com/hashicorp/vault/blob/main/sdk/framework/backend.go#L97
