### ISSUE TITLE
Show token ID (maybe other details) for admin token

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#36]
I suggest that we use some of the code for rotating admin tokens to show the token ID, and perhaps other details in the `vault read artifactory/admin/config` output. It wouldn't take much effort to move that parsing capability out and use it. Before I add that capability, I wanted to know if it was something that is desirable or "undesirable" ;) 

I am sitting here looking at ~50 access tokens with the username "admin" .... in addition to #34 which would allow me to *name* the admin access token (and maintain that name through rotation), I think it would be useful if I could see which token ID vault is using, specifically. (since we rotated, the sha256 is useless to us) ;)

**Comment by TJM** [comment]
@alexhung Does that mean that you think its a good idea? I think it wouldn't be too hard to code it (5mins) it looks like I put the JWTParse into the backend anyhow, so it is just a matter of adding a few lines to display the new outputs... and of course whether that changes anything for documentation/screenshots?

**Comment by alexhung** [comment]
@TJM Yes, I think if these information is useful to the users (e.g. you) and I think we should implement them. I welcome suggestions like this because you guys are the ones who use the plugin day in, day out, and more in tune to what are useful (or not).
