### ISSUE TITLE
Local Testing discussion

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#38]
I think the first step to being able to do automated tests would be to define what a local test environment would look like.

I suggest using something like minikube or kind (especially since kind has a built-in gitlab-action)... then install artifactory-jcr helm chart. (since that doesn't require a license)

I think we just need to figure out how to "bootstrap" it so that there isn't a bunch of interactive tasks.

Can we get any help from the artifactory devs on how we might manage that?
We (our mutual customer) also has Artifactory Enterprise, and has completely automated the setup, but that is a lot of custom terraform code (with a lot of shell script resources)... licenses, etc... seems like a lot of unnecessary overhead.

I think the first step will be trying to get the initial admin token -- https://jfrog.com/knowledge-base/artifactory-how-to-create-an-admin-token-without-using-the-ui/

... then feeding that back into the `make setup` (see #37)

Then, of course, we need to figure out what we are going to test... how many versions, etc etc... but I think getting a working Artifactory stood up is a crucial step.

**Comment by alexhung** [comment]
In the Terraform provider we use this [script](https://github.com/jfrog/terraform-provider-artifactory/blob/master/scripts/run-artifactory.sh) to spin up Docker containers. If there's a Docker image for JCR then we can re-use the script (with some modifications).

This is what I use for my local development environment so the challenge here is really getting a license-less instance up and running.

**Comment by alexhung** [comment]
Well, this is the Docker image: `docker pull releases-docker.jfrog.io/jfrog/artifactory-jcr:latest` So we can copy the script from TF repo to here and modified it so we pull the JCR image and spin up only one container.

**Comment by TJM** [comment]
I was just using `helm install artifactory jfrog/artifactory-jcr` ... but I was having issues getting the initial admin token. the procedure documented in the KB (link) doesn't work. I created a ticket #238182 to track that. I am not 100% sure I am doing it right.

**Comment by TJM** [comment]
```bash
touch var/bootstrap/etc/access/keys/generate.token.json; retries=100; while test $retries -gt 0; do test -f var/bootstrap/etc/access/keys/token.json && cat var/bootstrap/etc/access/keys/token.json || sleep 1 && retries=$((retries-1)) && echo -n $retries. >&2; done
```

... this is what I have been playing with to try to "get initial admin token" ... with hopes I could pass this into the container and basically just retrieve the token with a single kubectl exec command (or in your case docker exec?)

**Comment by alexhung** [comment]
If you take a look into the script I referenced earlier, you will see we use the private/UI api to do that 😄 .

**Comment by TJM** [comment]
Sorry, I just realized "script" was a link. That is almost exactly the same thing we came up with, except we used the "cookiejar" option instead of manually parsing/creating the cookies. As it turns out, its actually a lot easier than my previous note... because the file has to be there at startup time (artifactory.preStartCommand), you can just wait till the instance is ready, then grab the file.

something like:

```
kubectl wait --timeout=600s --for=condition=ready pod -l app=artifactory,component=artifactory && kubectl exec -it artifactory-0 -- cat var/etc/access/keys/token.json
```

... but yeah, the "getAccessKeys.sh" can work quite nicely as well. Do we want to use the raw docker container (and have to deal with our own database) or just the helm chart? I was just going to use kind or minikube and the helm chart. Also since the parts that we are trying to do are irrelevant for licensing purposes, we can actually use regular artifactory.

**Comment by alexhung** [comment]
The Docker container is self-contained. There's no need to deal with a separate database. Hence we use it for local development as well as CI testings.
