### ISSUE TITLE
Admin Token Expiration or auto-rotation

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#42]
The "admin" token we create in artifactory to configure the aritifactory-secrets-engine in Vault appears to expire after 1 year from issue. Is there a way to automatically renew those tokens? We actually have a "security policy" that ours are supposed to last no more than 30 days, so it is more than just once per year. I think we can just call the `/artifactory/config/rotate` path or function on a periodic basis, but I am not sure how that would be managed.

**Comment by alexhung** [comment]
@TJM Manually calling the `vault write -f artifactory/config/rotate` periodically would work but ideally creating an auth token with the 30 days expiry is better. You can do this either via the web UI or API.

Just be aware of this: https://www.jfrog.com/confluence/display/JFROG/Access+Tokens#AccessTokens-GeneratingExpirableTokens

**Comment by TJM** [comment]
This may be a lost cause, I am holding out waiting for a response from "engineering" 🤞

At a minimum, I think we should parse the JWT token's expiration date, and display it (that would be easy), and maybe even "WARN" the user when they configure an admin token that it has an expiration date (assuming it does). Of course that would all be lost for anyone doing automation. 🤷

**Comment by TJM** [comment]
I was given the following in my support request:
> Thank you for your patience on this matter. There is a [LifetimeWatcher](https://github.com/hashicorp/vault/blob/main/api/lifetime_watcher.go) mechanism in the existing [Go client library ](https://github.com/hashicorp/vault/tree/main/api)to renew tokens and other credential leases periodically. We have examples of how it can be used:
[simple case](https://github.com/hashicorp/vault-examples/blob/main/examples/token-renewal/go/example.go) (just renewing the authentication token)
[complex case](https://github.com/hashicorp/hello-vault-go/tree/main/sample-app#4-examine-the-logs-for-renew-logic) (renewing auth token and a child dynamic secret lease)
At the moment, unfortunately, the automated token renewal is not supported in other languages. We have also just released a couple new OpenAPI-based client libraries to public beta ([vault-client-go](https://github.com/hashicorp/vault-client-go/) and [vault-client-dotnet](https://github.com/hashicorp/vault-client-dotnet)). For the GA release we are planning to add a more developer-friendly token-renewal mechanism to both. More languages will be supported in the future with OpenAPI. I hope these information are helpful and can give you a head start with developing a plugin that could rotate admin token automatically. Thanks again for reaching out to us. Let me know if it would ok to resolve this ticket today.

**Comment by alexhung** [comment]
Sound promising.

**Comment by TJM** [comment]
eh, I think their example is for vault agent (or vault as a client). For now, I have added the `exp` (unixtime) and `expires` (human readable) field to the `vault read artifactory/config/admin` output. We have added warning(s) to the README. I think we are good on this. I am going to just close this instead of pursuing it further.
