### ISSUE TITLE
Artifactory version

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#48]
```
[tmcneely@local ~]$ docker pull releases-docker.jfrog.io/jfrog/artifactory-jcr:latest
latest: Pulling from jfrog/artifactory-jcr
Digest: sha256:d9ec79a9613627b17a27ae7bbc7cfb7de41cf998e04a7d7bbf945dc3dc3d952c
Status: Image is up to date for releases-docker.jfrog.io/jfrog/artifactory-jcr:latest
releases-docker.jfrog.io/jfrog/artifactory-jcr:latest
[tmcneely@local ~]$ docker images | grep jfrog
releases-docker.jfrog.io/jfrog/artifactory-jcr   7.55.7    d4807e14cca2   34 hours ago   1.63GB
releases-docker.jfrog.io/jfrog/artifactory-jcr   latest    803ee2eab100   6 days ago     1.63GB
releases-docker.jfrog.io/jfrog/artifactory-jcr   7.49.10   9adc79e21925   9 days ago     1.57GB
releases-docker.jfrog.io/jfrog/artifactory-jcr   7.55.2    7eda28873e4f   2 weeks ago    1.63GB
releases-docker.jfrog.io/jfrog/artifactory-jcr   7.39.10   3a88970e5f76   7 months ago   1.26GB
```

... I wonder whether something just broken during the 7.55.7 release? I was thinking of changing the default value for ARTIFACTORY_VERSION to `latest`, then maybe adding a `docker pull` to ensure it updates, but thought I would ask about that.

Tommy

**Comment by alexhung** [comment]
@TJM You know, I have no idea. @danielmkn may have more insight.

**Comment by TJM** [comment]
I would also like to be able to query (maybe against the docker api) what other tags the `latest` version actually has, instead of leaving a bunch of dangling images that used to be tagged "latest" each time it updates. I wonder how much effort that would be? :)

**Comment by alexhung** [comment]
@TJM So @danielmkn has this brilliant idea to query the JFrog Helm Chart to get latest version. You can curl [this yaml file](https://github.com/jfrog/charts/blob/master/stable/artifactory-jcr/Chart.yaml#L2) and pipe it to yq.

**Comment by alexhung** [comment]
😆 This is pretty much how we get latest version for our CI/CD pipeline

**Comment by alexhung** [comment]
@TJM I think it isn't unreasonable to ask dev to install yq for setting up a development/testing environment. Helm, may be a bridge too far.

**Comment by TJM** [comment]
```
[tmcneely@local ~]$ curl -u anonymous: -s https://releases-docker.jfrog.io/v2/jfrog/artifactory-jcr/tags/list
{
  "name" : "jfrog/artifactory-jcr",
  "tags" : [ "6.15.0", "6.15.1", "6.15.2", "6.16.0", "6.16.2", "6.17.0", "6.17.1", "6.17.4", "6.18.0", "6.18.1", "6.18.5", "6.19.0", "6.19.1", "6.19.3", "6.20.0", "6.20.1", "6.20.4", "6.21.0", "6.21.1", "6.22.0", "6.22.2", "6.23.0", "6.23.1", "6.23.13", "6.23.15", "6.23.16", "6.23.18", "6.23.19", "6.23.21", "6.23.23", "6.23.25", "6.23.28", "6.23.3", "6.23.31", "6.23.33", "6.23.36", "6.23.37", "6.23.38", "6.23.41", "6.23.42", "6.23.7", "7.10.2", "7.10.5", "7.10.6", "7.11.2", "7.11.5", "7.11.7", "7.11.8", "7.12.10", "7.12.5", "7.12.6", "7.12.8", "7.12.9", "7.15.3", "7.15.4", "7.15.5", "7.16.3", "7.16.6", "7.17.11", "7.17.12", "7.17.13", "7.17.14", "7.17.16", "7.17.4", "7.17.5", "7.17.9", "7.18.11", "7.18.12", "7.18.3", "7.18.5", "7.18.6", "7.18.7", "7.18.9", "7.19.10", "7.19.12", "7.19.13", "7.19.4", "7.19.8", "7.19.9", "7.2.0", "7.2.1", "7.21.12", "7.21.13", "7.21.20", "7.21.25", "7.21.27", "7.21.3", "7.21.5", "7.21.7", "7.21.8", "7.23.3", "7.23.7", "7.23.8", "7.24.3", "7.24.6", "7.24.7", "7.25.5", "7.25.6", "7.25.7", "7.25.9", "7.27.10", "7.27.15", "7.27.3", "7.27.6", "7.27.9", "7.29.10", "7.29.7", "7.29.8", "7.29.9", "7.3.2", "7.31.10", "7.31.11", "7.31.12", "7.31.13", "7.31.16", "7.33.12", "7.33.8", "7.33.9", "7.35.1", "7.35.2", "7.37.13", "7.37.14", "7.37.15", "7.37.16", "7.37.17", "7.38.10", "7.38.16", "7.38.17", "7.38.7", "7.38.8", "7.39.10", "7.39.4", "7.4.1", "7.4.3", "7.41.12", "7.41.13", "7.41.14", "7.41.4", "7.41.6", "7.41.7", "7.46.10", "7.46.11", "7.46.17", "7.46.20", "7.46.21", "7.46.22", "7.46.23", "7.46.3", "7.46.6", "7.46.8", "7.46.9", "7.47.10", "7.47.11", "7.47.12", "7.47.14", "7.47.15", "7.47.16", "7.49.10", "7.49.3", "7.49.5", "7.49.6", "7.49.8", "7.5.5", "7.5.7", "7.55.2", "7.55.3", "7.55.4", "7.55.6", "7.55.7", "7.6.1", "7.6.2", "7.6.3", "7.7.3", "7.7.8", "7.9.0", "7.9.1", "7.9.2", "latest" ]
}
```
.. but then you are left trying to find latest again :)

**Comment by TJM** [comment]
> @TJM I think it isn't unreasonable to ask dev to install yq for setting up a development/testing environment. Helm, may be a bridge too far.

in the helm chart/yq model, how are you finding the latest?

**Comment by alexhung** [comment]
```sh
curl -s 'https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-jcr/Chart.yaml' 2>&1 | yq r - 'appVersion'
```

**Comment by TJM** [comment]
> ```shell
> curl -s 'https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-jcr/Chart.yaml' 2>&1 | yq r - 'appVersion'
> ```

```shell
[tmcneely@local ~]$ curl -s 'https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-jcr/Chart.yaml' 2>&1 | yq r - 'appVersion'

Error: 1:1: invalid input text "r"
[tmcneely@local ~]$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.30.4
```

There goes the issue with "yq" there are different versions, that are incompatible.  It might be better to just parse it out with awk or something :)

**Comment by alexhung** [comment]
Sure, the parsing is straightforward. I'm more concerned that it isn't really the latest.

**Comment by TJM** [comment]
I think the right way to do this would be to make a "Dockerfile" (that we never intend to build), but that the magical version updater thingy will find and update for us with PRs?

**Comment by alexhung** [comment]
Just me diving into the jq rabbit hole:

```sh
curl -u anonymous: -s 'https://releases-docker.jfrog.io/v2/jfrog/artifactory-jcr/tags/list' 2>&1 | jq '.tags | map(select(. | index("latest") | not)) | sort_by(values | split(".") | map(tonumber)) | last'
```

**Comment by TJM** [comment]
So, I love that, but that really isn't much better than `latest`, if JFrog releases an incompatible release (8.0.0?), we will have to scramble. That is why I was trying to stick with a known working version, that we could run "tests" against before merging into master.

**Comment by TJM** [comment]
With that fancyness in place...

```console
[tmcneely@local artifactory-secrets-plugin]$ make artifactory ARTIFACTORY_VERSION=latest
ARTIFACTORY_IMAGE=artifactory-jcr
ARTIFACTORY_VERSION=7.55.7
### Wait for Artifactory to start ###
```

**Comment by alexhung** [comment]
> is it inception to pull artifactory from artifactory?

It's 🐢 all the way down!

**Comment by TJM** [comment]
Closed by #48

**Comment by TJM** [comment]
I mean, I think so. Did you enable dependabot in the settings? (or can you get someone to if you don't have access?)

**Comment by alexhung** [comment]
![Screenshot 2023-03-20 at 10 44 27 AM](https://user-images.githubusercontent.com/27263/226423651-3145c565-d919-42a1-ae3e-bfd9f98326f7.png)

Not yet with "Dependabot version updates". I skimped the doc last week and look like it's more than just press a button 😄 So I need to block out some time this week to set it up.

**Comment by TJM** [comment]
True, it may be more involved, and it will call out all our other out of date dependencies (which is probably a good thing). Up to you on whether this particular issue can be resolved. I think we are good to go on it.

**Comment by alexhung** [comment]
Add [this file](https://github.com/jfrog/artifactory-secrets-plugin/blob/master/.github/dependabot.yml). Let's see if that works.

**Comment by alexhung** [comment]
@TJM The bot works! https://github.com/jfrog/artifactory-secrets-plugin/pull/58

And plenty of PRs for Go dependencies 😄
