### ISSUE TITLE
dev version suggestion

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#67]
It might be good to indicate "dev" in the non-released version somehow?

- maybe add `-dev`
- maybe `-dev-DATESTAMP`? 
- Maybe git hash?

Some combination? Something else? :)

**Comment by alexhung** [comment]
Agree. Depends on your use cases, what would you suggest? I am leaning towards `-dev-<short-hash>`

**Comment by alexhung** [comment]
I assume you're referring to builds made by `make build` command? Or some other process via `go test` for example?

**Comment by TJM** [comment]
Yep, `-dev-<short-hash>` seems as good as anything for now. Yes, I was referring to the "`make build`" version (or just `make`), but where I noticed it was `make upgrade` ... it still shows the same version (currently `v0.2.13`).

**Comment by alexhung** [comment]
Sounds like `make register` need to include `-version=${NEXT_VERSION}`
