### ISSUE TITLE
make acceptance uses inconsistent env variables

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#70]
as per the conversation in #66 ... we found that `make acceptance` uses different variables than the rest.

The rest of the make targets use:
> `JFROG_ACCESS_TOKEN` / `ARTIFACTORY_URL`

make acceptance uses:
> `ARTIFACTORY_ACCESS_TOKEN` / `JFROG_URL`

Should we change the test code to `ARTIFACTORY_URL` and `JFROG_ACCESS_TOKEN` to match the test, or change everything to JFROG_blah or ARTIFACTORY_blah. It does seem a bit strange to use ARTIFACTORY_ for one and JFROG_ for the other.

**Comment by TJM** [comment]
I am not *deciding* on changing acceptance, that was just where I was at with my other PR, so I thought I'd push it up as an example.

**Comment by alexhung** [comment]
Ideally, they should all be prefixed with `JFROG_` for consistency, while still supporting `ARTIFACTORY_`?

I'm ok to do this in multiple small steps, e.g. fix acceptance tests first, then harmonize everything to `JFROG_` prefix.
