### ISSUE TITLE
GPG Signed *binary* sha256sums in release

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#81]
It would be a "Good Thing" (tm) if we could get a GPG signed `sha256sum` of the plugin *binary*, since that is what Vault is looking for. We are currently publishing the sha256sum of the zip file, which is *good*, and I don't suggest changing that, but it should also be GPG signed. ;)

I saw a public key in the release and figured it was time we started doing it ;)

**Comment by alexhung** [comment]
Progress update: GoReleaser currently doesn't really support packaging additional files *inside* the same folder as the binary. Thus making it impossible to include checksum and signature files in the zip file.

However, I can change the process to *not* make a zip file. This way GoReleaser will create a checksum file with checksums for the binary files. Then signs that checksum file.

Example of the new checksum file (`artifactory-secrets-plugin_0.2.17_checksums.txt`):

```
036f060de5d821137a354a72e4a2196a1caeb72ae59ddbd01d3a9c9e4555b1f9  artifactory-secrets-plugin_0.2.17_darwin_amd64
09be7b7bb35eaf060b0c00569f2233697b020e9b65c9998165f38af84e96f9ed  artifactory-secrets-plugin_0.2.17_windows_arm64.exe
34f86d8fe81c5ca65cb7b6d3c876dba47e70673afb7a12ed41216eaeee441b3d  artifactory-secrets-plugin_0.2.17_windows_amd64.exe
39e1c47c6eab54d611ae11af8ded7fcb664ebe4d0383fe4d289a44b8920e36a3  artifactory-secrets-plugin_0.2.17_darwin_arm64
59c20d12b687adbf83af4c7887e766527720079e8077185c04e2a0e92911dc37  artifactory-secrets-plugin_0.2.17_windows_armv6.exe
6408b12115120f4c1f557690d8c5948168daa8337dafc8823ad1efc8b70ac8a7  artifactory-secrets-plugin_0.2.17_linux_amd64
669a0c0df7198f5747ec72baec773ceb759c42c33112d3365b84d4a8af2d891b  artifactory-secrets-plugin_0.2.17_windows_386.exe
68ddffba5120987bbebd2dd7ec045400ac7f245f9b0436c4d1a0d5a4a9705e3b  artifactory-secrets-plugin_0.2.17_linux_386
70a6d79e6b79cd5d3ada2b6d27e90c5c9b83b6f0ee3d351e89977c8294aba910  artifactory-secrets-plugin_0.2.17_linux_arm64
96692fe9fba8ccead5717314182013bda342ae8b2b2c6696869663367659e3ed  artifactory-secrets-plugin_0.2.17_freebsd_arm64
b975639cc0ce9e1d2ff10aa2ea1013e6fb0a9500c0ec8b8cf251fa0242fcb27d  artifactory-secrets-plugin_0.2.17_linux_armv6
c023c11446ff35d648ba0c65d975ddb54a51110fc701e96379cec4c78f761fe3  artifactory-secrets-plugin_0.2.17_freebsd_386
dea595c372789fd134d20cdc2d369a36d0189e31db4940b9e48e9d584a544f74  artifactory-secrets-plugin_0.2.17_freebsd_amd64
fc7d4093aef8209c1b61596b44bd727a09689d3dccc239e8b0f62b5c8888a58e  artifactory-secrets-plugin_0.2.17_freebsd_armv6
```

What do you think? My take is that this gives you the signed checksum for each binary. You do need to do some awk/grep to extract the checksum from the text file for the binary you are interested in. And the files uploaded to GitHub are the actual binaries, not zips.

**Comment by TJM** [comment]
That looks great. We already do something similar for the zip file checksums anyhow, and I am not sure if we need to zip the binaries?

**Comment by alexhung** [comment]
The zip file is part of GoReleaser's feature and was used because it's just a simple config setting. In reality the binary sizes are pretty small so the gain in file size is not massive.

I'll try to create a PR this week.

The main change is the removal of zip file so any scripts that assume the present of zip file needs to be updated.

**Comment by TJM** [comment]
Good thing it's not 1.0, yet, right!?
