### ISSUE TITLE
Embed current version changes (like from the changelog) in release

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-secrets-plugin#83]
When creating a release, it would be a good thing if all of the changes since the last release, which are also included in the CHANGELOG.md for this version, were included into the [release notes](https://github.com/jfrog/artifactory-secrets-plugin/releases/tag/v0.2.16). Currently they frequently only have the current commit (Update Changelog) is included, and is fairly useless:

**Comment by alexhung** [comment]
Good idea.
